
"use client"
import './globals.css'
import { Inter } from 'next/font/google'

// import chakra providers from our custom providers
import {ChakraProvider} from "@/providers"
import { BaseLayout } from '@/layouts'
import TranslationProvider from '@/providers/translation'
import { Suspense } from 'react'
import { queryClient } from '@/lib/react-query'
import { QueryClientProvider } from 'react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ChakraProvider>
        <Suspense fallback={<div>Loading...</div>}>
          <QueryClientProvider
              client={queryClient}
          >
            <TranslationProvider locale="en" >
              <BaseLayout>
                {children}
              </BaseLayout>
            </TranslationProvider>
          </QueryClientProvider>
        </Suspense>
      </ChakraProvider>
    </html>
    
  )
}
